# Generated by Django 5.1.5 on 2025-01-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='tovar_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
